// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUoQ5k9bxxwcAv_xnHV5OSoNPydmcmdYk',
    appId: '1:389233029159:web:ee0e94975323fbf02b5e02',
    messagingSenderId: '389233029159',
    projectId: 'pickletrack-268a2',
    authDomain: 'pickletrack-268a2.firebaseapp.com',
    storageBucket: 'pickletrack-268a2.firebasestorage.app',
    measurementId: 'G-NMLY8WZFTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Pc9iY9YyWZaL37-XeIqdFI8WoGNu3x0',
    appId: '1:389233029159:android:5b8da762e90beca02b5e02',
    messagingSenderId: '389233029159',
    projectId: 'pickletrack-268a2',
    storageBucket: 'pickletrack-268a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClCS69geyYJzRoS-agD9ope2ntikG3YE8',
    appId: '1:389233029159:ios:a39cd6c5d0b337f92b5e02',
    messagingSenderId: '389233029159',
    projectId: 'pickletrack-268a2',
    storageBucket: 'pickletrack-268a2.firebasestorage.app',
    iosBundleId: 'com.example.mypickletrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClCS69geyYJzRoS-agD9ope2ntikG3YE8',
    appId: '1:389233029159:ios:a39cd6c5d0b337f92b5e02',
    messagingSenderId: '389233029159',
    projectId: 'pickletrack-268a2',
    storageBucket: 'pickletrack-268a2.firebasestorage.app',
    iosBundleId: 'com.example.mypickletrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUoQ5k9bxxwcAv_xnHV5OSoNPydmcmdYk',
    appId: '1:389233029159:web:a698e986e87a69762b5e02',
    messagingSenderId: '389233029159',
    projectId: 'pickletrack-268a2',
    authDomain: 'pickletrack-268a2.firebaseapp.com',
    storageBucket: 'pickletrack-268a2.firebasestorage.app',
    measurementId: 'G-MTENBPYLWY',
  );

}